CHANGELOG.md
README.md
build.gradle
src/main/resources/deb/control.ftl
src/test/groovy/com/netflix/gradle/plugins/deb/TemplateHelperSpec.groovy

bad depends.
Also verified that jdeb does omit the empty depends block from the final debian

Fixes #96. Pass an empty Depends to jdeb so it doesn't append 

---

src/main/groovy/com/netflix/gradle/plugins/deb/DebCopyAction.groovy

The console object introduced in fdb9d79 sent jdeb's debug messages as 'warn' messages. This output includes a detailed file listing and becomes very verbose. For one of our projects we were getting 16MB of output when building a deb.

Fix jdeb log levels

---

src/main/groovy/com/netflix/gradle/plugins/deb/DebCopyAction.groovy
src/main/groovy/com/netflix/gradle/plugins/packaging/SystemPackagingExtension.groovy
src/main/groovy/com/netflix/gradle/plugins/packaging/SystemPackagingTask.groovy
src/test/groovy/com/netflix/gradle/plugins/deb/DebPluginTest.groovy

Regarding #109 here is a PR allowing to add arbitrary files to the debian control directory.
For example, using this, one is able to put a `changelog` file in there.
Please tell me if you're willing to merge this and if more changes are needed.
Cheers

Can add supplementary files to debian control

---

Plugin-Deb.md
src/main/groovy/com/netflix/gradle/plugins/deb/Deb.groovy
src/main/groovy/com/netflix/gradle/plugins/deb/DebCopyAction.groovy
src/main/groovy/com/netflix/gradle/plugins/packaging/SystemPackagingExtension.groovy
src/main/resources/deb/control.ftl
src/test/groovy/com/netflix/gradle/plugins/deb/DebPluginTest.groovy
src/test/groovy/com/netflix/gradle/plugins/deb/TemplateHelperSpec.groovy

Adds support for user-defined fields in the control file (and resultant binary package)
https://www.debian.org/doc/debian-policy/ch-controlfields.html#s5.7
fixes #131
cc @rspieldenner @jkschneider @DanielThomas

#131 - user-defined control fields

---

src/main/groovy/com/netflix/gradle/plugins/deb/validation/DebPackageNameAttributeValidator.groovy
src/test/groovy/com/netflix/gradle/plugins/deb/validation/DebPackageNameValidatorTest.groovy
src/test/groovy/com/netflix/gradle/plugins/deb/validation/DebTaskPropertiesValidatorIntegrationTest.groovy

Hello,
I discovered that no debian packages with a name including capital letters like `foo-BAR` returns the error:
> Invalid package name 'foo-BAR' - a valid package name must start with an alphanumeric character, have a length of at least two characters and only contain [A-Za-z0-9.+-]
In the error it is stated, that it is valid to use capital letters. 
Because of that I fixed to regex to validate them as well. 
Regards

fixed: no capitals are usable in debian package names

---

build.gradle
src/main/groovy/com/netflix/gradle/plugins/deb/DebCopyAction.groovy
src/main/groovy/com/netflix/gradle/plugins/docker/DockerCopyAction.groovy
src/main/groovy/com/netflix/gradle/plugins/packaging/AbstractPackagingCopyAction.groovy
src/main/groovy/com/netflix/gradle/plugins/packaging/SystemPackagingExtension.groovy
src/main/groovy/com/netflix/gradle/plugins/packaging/SystemPackagingTask.groovy
src/main/groovy/com/netflix/gradle/plugins/rpm/RpmCopyAction.groovy
src/main/resources/deb/control.ftl
src/test/groovy/com/netflix/gradle/plugins/deb/DebPluginTest.groovy
src/test/groovy/com/netflix/gradle/plugins/packaging/SystemPackagingBasePluginTest.groovy
src/test/groovy/com/netflix/gradle/plugins/rpm/RpmPluginTest.groovy

FIxes #148 
Changes the behavior of the provides directive to build a list and provide that as a comma-delimited list in the resultant spec and control files for RPMs and DEBs respectively.
This does not currently allow for the RPM ability to declare a version along with the package name. DEB packages do not take a version in provides (provides is commonly used to provide "virtual packages" that allow multiple packages to satisfy a single dependency. eg vim, nvim, neovim, may all declare that they provide "vi" and "editor", and one may declare a dependency on that virtual package to ensure at least ONE of those choices is installed).
This no longer adds the package being built to the Provides: field as packages implicitly provide themselves
cc @rspieldenner @jkschneider @DanielThomas …

#148 - make provides accept multiple values

---

src/main/groovy/com/netflix/gradle/plugins/packaging/SystemPackagingExtension.groovy
src/test/groovy/com/netflix/gradle/plugins/packaging/SystemPackagingExtensionTest.groovy

This pull request adds the documented but missing method
`requires(String packageName, String version)` to 
`com.netflix.gradle.plugins.packaging.SystemPackagingExtension` closes #169

Add missing requires() method

---

src/main/groovy/com/netflix/gradle/plugins/packaging/Dependency.groovy
src/test/groovy/com/netflix/gradle/plugins/deb/DebPluginTest.groovy

It is possible for Debian package to have alternatives for dependencies. I don't know much about RPM, but I found info that although a similar feature has just appeared, its use is limited yet.
So I propose to support this feature for Debian now.

Enable alternative dependencies for debian

---

src/main/groovy/com/netflix/gradle/plugins/packaging/Link.groovy

The Link class required equals and hashcode to be usable
with task inputs. It would cause perpetual out-of-date
condition for tasks where symlinks were declared in the
package definition.

Fix Link class to be usable as task input

---

src/main/groovy/com/netflix/gradle/plugins/deb/DebCopyAction.groovy
src/main/groovy/com/netflix/gradle/plugins/deb/MaintainerScriptsGenerator.groovy
src/main/groovy/com/netflix/gradle/plugins/packaging/AbstractPackagingCopyAction.groovy
src/main/groovy/com/netflix/gradle/plugins/packaging/SystemPackagingExtension.groovy
src/main/groovy/com/netflix/gradle/plugins/rpm/RpmCopyAction.groovy
src/main/groovy/com/netflix/gradle/plugins/utils/ApacheCommonsFileSystemActions.groovy
src/main/groovy/com/netflix/gradle/plugins/utils/FileSystemActions.groovy
src/test/groovy/com/netflix/gradle/plugins/deb/DebPluginTest.groovy
src/test/groovy/com/netflix/gradle/plugins/deb/MaintainerScriptsGeneratorSpec.groovy
src/test/groovy/com/netflix/gradle/plugins/packaging/SystemPackagingExtensionTest.groovy

This PR defines four new properties that allow defining the complete maintainer script files.
* `preInstallFile`
* `postInstallFile`
* `preUninstallFile`
* `postUninstallFile`
These directives are only supported when building a deb and allow scripts to be written with shebang lines other than `#!/bin/sh`:
```py
#!/usr/bin/env python3
print("Starting to install...")
```
An `IllegalStateException` is thrown when multiple of the same file is defined, or commands and the file are defined at the same time. For example:
```console
* Where:
Build file '/Projects/sample-package/build.gradle' line: 26
* What went wrong:
A problem occurred evaluating root project 'sample-package'.
> Cannot specify PreInstall File and PreInstall Commands
```
Attempting to use the new directives in a custom `Rpm` …

Allow Defining Complete Maintainer Scripts for Debian

---

src/main/groovy/com/netflix/gradle/plugins/packaging/SystemPackagingExtension.groovy

Add the Input and Optional annotations to the new maintainer scripts declarations to better utilize gradle's UP-TO-DATE checks.

Add Input and Optional to Maintainer Scripts

---

src/main/resources/com/netflix/gradle/plugins/daemon/log-run.tpl
src/test/groovy/com/netflix/gradle/plugins/daemon/OspackageDaemonPluginSpec.groovy

it is unnecessary and fails with common nobody:nogroup users

dont force "nobody" group

---

src/main/groovy/com/netflix/gradle/plugins/packaging/SystemPackagingTask.groovy

Currently the file directives for maintainer scripts must be defined on `buildDeb`. 
This change allows them to be defined on `ospackage`:
```gradle
ospackage {
preInstallFile file('scripts/preinstall.sh')
}
```

Add Mappings for ospackage Block File Directives

---

build.gradle
src/main/groovy/com/netflix/gradle/plugins/rpm/Rpm.groovy
src/main/groovy/com/netflix/gradle/plugins/rpm/RpmCopyAction.groovy

This is an implementation to resolve issue https://github.com/nebula-plugins/gradle-ospackage-plugin/issues/164 .  It makes use of the new Builder.addChangeLog() method in redline-1.2.3.

Add changelogFile member to Rpm, and use redline-1.2.4 for support

---

src/main/groovy/com/netflix/gradle/plugins/packaging/SystemPackagingTask.groovy

Fix for issue #174 
I made several test and looks like all works fine.

Remove duplication of prefixes in rpm

---

src/main/groovy/com/netflix/gradle/plugins/rpm/RpmCopyAction.groovy

There is bug - directory permissions must be set using dirMode instead of fileMode field.
Fix line
int dirMode = lookup(specToLookAt, 'fileMode') ?: dirDetails.mode
Change to
int dirMode = lookup(specToLookAt, 'dirMode') ?: dirDetails.mode

Fix directory permissions to be set using dirMode instead of fileMode field (in RpmCopyAction.groovy)

---

src/main/groovy/com/netflix/gradle/plugins/rpm/RpmCopyAction.groovy
src/test/groovy/com/netflix/gradle/plugins/rpm/RpmPluginTest.groovy

Fixed issue with addParentDirs and createDirectoryEntry properties not being handled properly.
Also added test to catch future regression. Fixes issues #124 and #212 and #197.

Fixed issue with addParentDirs and createDirectoryEntry properties

---

src/main/groovy/com/netflix/gradle/plugins/packaging/SystemPackagingExtension.groovy

This change allows gradle to track content changes of the files in addition to path changes of the property. Fixes #217

Mark MaintainerScripts with InputFile

---

src/main/groovy/com/netflix/gradle/plugins/deb/MaintainerScriptsGenerator.groovy
src/main/groovy/com/netflix/gradle/plugins/packaging/SystemPackagingTask.groovy
src/test/groovy/com/netflix/gradle/plugins/application/OspackageApplicationPluginLauncherSpec.groovy
src/test/groovy/com/netflix/gradle/plugins/deb/MaintainerScriptsGeneratorSpec.groovy

When neither script command and script file is not defined.
Fixing 'maintainer-script-empty' warning from lintian.

Do not create empty maintainer scripts for deb-package

---

src/test/groovy/com/netflix/gradle/plugins/rpm/RpmPluginTest.groovy

Add assertions to verify given distribution is set in RPM. Inspired by #144.

Add Distribution Assertions to RPMPluginTest

---

src/main/groovy/com/netflix/gradle/plugins/deb/Deb.groovy
src/main/groovy/com/netflix/gradle/plugins/deb/DebCopyAction.groovy
src/test/groovy/com/netflix/gradle/plugins/deb/DebPluginTest.groovy

* Uses archivePath to get name of debian, and declares corresponding changes file as task output
* Removes stale TODO
* Removes redundant log statement
* Closes #114

Declare Deb .changes File as OutputFile

---

src/main/groovy/com/netflix/gradle/plugins/deb/DebCopyAction.groovy
src/main/groovy/com/netflix/gradle/plugins/deb/InstallLineGenerator.groovy
src/main/resources/deb/postinst.ftl
src/test/groovy/com/netflix/gradle/plugins/deb/InstallLineGeneratorSpec.groovy
src/test/groovy/com/netflix/gradle/plugins/deb/TemplateHelperSpec.groovy

To facilitate easier testing, move the conditional install-line builder logic from postinst.ftl to its own class. 
Support installing directories with custom groups as per the [install docs](https://www.gnu.org/software/coreutils/manual/html_node/install-invocation.html) and #80.

Support Directory Installation with Custom Groups

---

src/main/groovy/com/netflix/gradle/plugins/packaging/ProjectPackagingExtension.groovy
src/main/groovy/com/netflix/gradle/plugins/packaging/SystemPackagingTask.groovy
src/main/groovy/com/netflix/gradle/plugins/utils/FromConfigurationFactory.groovy
src/main/groovy/com/netflix/gradle/plugins/utils/JavaNIOUtils.groovy
src/test/groovy/com/netflix/gradle/plugins/deb/DebPluginTest.groovy
src/test/groovy/com/netflix/gradle/plugins/docker/OsPackageDockerPluginTest.groovy
src/test/groovy/com/netflix/gradle/plugins/rpm/RpmPluginTest.groovy

Closes #58 by supporting symlinks by default in the `from` block.
Notes:
* follows the convention of `ProjectPackagingExtension` of commenting out an overridden method
* `from` directives that do not have closures are redirected to `from` directives with a symlink-preserving closure
* `from` directives with closures are composed with the symlink-preserving closure
* symlink-preserving closure heavily inspired by workarounds proposed in #58.
* Possible issue (that also exists with the workarounds in #58): by default, symlinks are created as owned by `root/root`, whereas the default for other files is `$USER/0`

Support symlinks by default

---

build.gradle
src/test/groovy/com/netflix/gradle/plugins/rpm/RpmPluginTest.groovy

The [new release](https://github.com/craigwblake/redline/releases/tag/redline-1.2.5) of redline allows `~` in versions, which will let rpm and nebula-release-plugin users build without workarounds. 🎉 
Closes #213, also mentioned on #49.

Upgrade redline to allow ~ in version

---

src/main/groovy/com/netflix/gradle/plugins/deb/MaintainerScriptsGenerator.groovy
src/test/groovy/com/netflix/gradle/plugins/deb/DebPluginTest.groovy
src/test/groovy/com/netflix/gradle/plugins/deb/MaintainerScriptsGeneratorSpec.groovy

A regression was introduced for a previously untested feature in v4.3.0.
#203 no longer runs template generation if there are no commands, which works very well for preinst, prerm and postrm. The postinst template also has behavior for 'dirs' implemented, which would not run in v4.3.0 unless the user had also defined postInst commands.
This applies to debians only and includes a test to catch future regressions.

Run postinst script template generation when dirs present

---

src/main/groovy/com/netflix/gradle/plugins/daemon/DaemonDefinition.groovy
src/main/groovy/com/netflix/gradle/plugins/daemon/LegacyInstallCmd.groovy
src/main/groovy/com/netflix/gradle/plugins/daemon/OspackageDaemonPlugin.groovy
src/test/groovy/com/netflix/gradle/plugins/daemon/DaemonExtensionSpec.groovy
src/test/groovy/com/netflix/gradle/plugins/daemon/LegacyInstallCmdSpec.groovy
src/test/groovy/com/netflix/gradle/plugins/daemon/OspackageDaemonPluginLauncherSpec.groovy
src/test/groovy/com/netflix/gradle/plugins/daemon/OspackageDaemonPluginSpec.groovy

If a user supplies an `installCmd` in the daemon definition, use that in the postInstall script. Otherwise fall back to the existing behavior.

Extract LegacyInstallCmd, Add installCmd to Daemon Definition

---

src/main/groovy/com/netflix/gradle/plugins/rpm/RpmCopyAction.groovy

Currently, scriptlets are generated for all stages regardless of whether they do anything. This is best avoided.
Additionally, the `%pretrans` scriptlet is being treated the same as any other type of scriptlet. This is a bad idea, as there are conditions where a shell might not be present to run the `%pretrans` scriptlet. Moreover, it's recommended in the [Fedora Packaging Guidelines](https://fedoraproject.org/wiki/Packaging:Scriptlets#The_.25pretrans_Scriptlet) that if a `%pretrans` scriptlet is required, it _must_ be written in Lua. This means it makes no sense to include the preamble added to the scriptlet by `scriptWithUtils`.

Avoid scriptlet generation; special-case %pretrans.

---

src/main/resources/deb/control.ftl
src/test/groovy/com/netflix/gradle/plugins/deb/DebPluginTest.groovy

This addresses issue #268. 
According to [Debian docs](https://www.debian.org/doc/manuals/maint-guide/dreq.en.html#control), the long `Description` field of the control file should be indented with spaces.
Before, the plugin would not correctly handle multiline `Description`, and as a result jDeb would complain with a cryptic message.
Now, the plugin supports multiline `Description` by correctly indenting with spaces.

Support multiline description in deb control file

---

src/main/groovy/com/netflix/gradle/plugins/packaging/AbstractPackagingCopyAction.groovy

Remove fallback call to org.gradle.api.internal.tasks.SimpleWorkResult. This is removed in 5.0 and means this plugin will now work with Gradle 4.2 (Released 2017-09-20) and later. [WorkResults](https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/WorkResults.html) was added in 4.2.

Gradle 5.0 Compatibility

---

.gitignore
src/main/groovy/com/netflix/gradle/plugins/daemon/DaemonTemplateTask.groovy
src/main/groovy/com/netflix/gradle/plugins/daemon/DaemonTemplatesConfigExtension.groovy
src/main/groovy/com/netflix/gradle/plugins/daemon/OspackageDaemonPlugin.groovy
src/main/groovy/com/netflix/gradle/plugins/daemon/TemplateHelper.groovy
src/test/groovy/com/netflix/gradle/plugins/daemon/OspackageDaemonPluginLauncherSpec.groovy
src/test/groovy/com/netflix/gradle/plugins/daemon/TemplateHelperSpec.groovy
src/test/resources/com/netflix/gradle/plugins/daemon/custom/initd.tpl
src/test/resources/com/netflix/gradle/plugins/daemon/custom/log-run.tpl
src/test/resources/com/netflix/gradle/plugins/daemon/custom/run.tpl

Historically OSPackage has provided templates for the daemon plugin:
`init`, `run`, `log-run`.
There is no easy way to override these.
This pull request suggest allows to set a property in build file as follows:
` daemonsTemplates.folder = '/com/netflix/gradle/plugins/daemon/custom'`
This will look for templates in the provided folder within the classpath (living basically in resources folder) or falling back to local filesystem in case users decide that's convenient for them. 
`daemonsTemplates.folder` is introduced in order to avoid breaking changes with the existing contract. Also simplifies things in cases where users set daemons as follows:
```
daemon {
daemonName = "foobaz" // default = packageName
command = "sleep infinity" // required
}
daemons {
daemon {
// daemonName default = …
```

Configurable template folder

---

src/main/groovy/com/netflix/gradle/plugins/deb/Deb.groovy
src/main/groovy/com/netflix/gradle/plugins/deb/DebCopyAction.groovy
src/main/groovy/com/netflix/gradle/plugins/deb/DebFileVisitorStrategy.groovy
src/test/groovy/com/netflix/gradle/plugins/deb/DebPluginTest.groovy

This allows mark files within a debian package as configuration ones. As it does only supports `CONFIG` string, the Deb-Plugin wiki page should be modified.  
Closes nebula-plugins/gradle-ospackage-plugin#118

Add support for config files on .deb

---

src/main/groovy/com/netflix/gradle/plugins/deb/Deb.groovy
src/main/groovy/com/netflix/gradle/plugins/packaging/SystemPackagingExtension.groovy
src/main/groovy/com/netflix/gradle/plugins/packaging/SystemPackagingTask.groovy
src/main/groovy/com/netflix/gradle/plugins/rpm/Rpm.groovy

Both tasks already support up-to-date check so only the annotation was
missing to make them cacheable.
By default, all the built-in archiving tasks are not cacheable as they
are usually quick so it's not worth it to make them cacheable. The
difference with Rpm and Deb is the output produced, if task is executed
twice from a clean workspace, is different because a time stamp is
inserted in the deb or rpm.
Making those task cacheable is worth it to not invalidate the tasks that
depends on the deb or rpm, they will be retrieved from the gradle cache
if it is enabled.

 Make Deb and Rpm tasks cacheable 

---

src/main/groovy/com/netflix/gradle/plugins/utils/GradleUtils.groovy
src/test/groovy/com/netflix/gradle/plugins/deb/DebPluginTest.groovy

The relative path in the FileCopyDetails can go outside the sourcebase directory with ../../path/to/file this can cause `String index out of range` exception or a `NoSuchFileException`.

Fix #321 copydetails relative path outside sourceBase

---

build.gradle
src/main/groovy/com/netflix/gradle/plugins/application/OspackageApplicationSpringBootPlugin.groovy
src/main/groovy/com/netflix/gradle/plugins/deb/Deb.groovy
src/main/groovy/com/netflix/gradle/plugins/deb/DebCopyAction.groovy
src/main/groovy/com/netflix/gradle/plugins/deb/validation/DebTaskPropertiesValidator.groovy
src/main/groovy/com/netflix/gradle/plugins/packaging/SystemPackagingExtension.groovy
src/main/groovy/com/netflix/gradle/plugins/packaging/SystemPackagingTask.groovy
src/main/groovy/com/netflix/gradle/plugins/rpm/Rpm.groovy
src/main/groovy/com/netflix/gradle/plugins/rpm/RpmCopyAction.groovy
src/test/groovy/com/netflix/gradle/plugins/application/OspackageApplicationSpringBootPluginLauncherSpec.groovy
src/test/groovy/com/netflix/gradle/plugins/rpm/RpmPluginIntegrationTest.groovy

For now, im using deprecation logger for `getVersion()` as it needs some work to avoid issues between `AbstractArchiveTask.getVersion()` `AbstractArchiveTask.getArchiveVersion()` and 
`SystemPackagingExtension.getVersion()`
Migrated other things such as `archiveClassifier` `archiveBaseName`

Gradle 6.1.x support - deprecation warning logger for now

---

src/main/groovy/com/netflix/gradle/plugins/deb/DebCopyAction.groovy
src/main/groovy/com/netflix/gradle/plugins/packaging/SystemPackagingExtension.groovy
src/test/groovy/com/netflix/gradle/plugins/deb/DebPluginTest.groovy
src/test/groovy/com/netflix/gradle/plugins/packaging/SystemPackagingBasePluginTest.groovy

Fixes #365.
My first PR, so any/all feedback appreciated! I tried to keep to the style already used and not do anything breaking.
* Adds logic to include the version for provides, if set, in the `DebCopyAction`. It is assumed this will always be an `=` relation, based on Debian packaging policy.
* Adds a new `provides(packageName, packageVersion)` method to the `SystemPackagingExtension`, assuming (again) this will always be an `=` relation, for both RPM and DEB (I have yet to see otherwise for RPM).
* Added test for provides with version for `buildDeb`
* Added test for propagation of provides with version from `ospackage` to `buildDeb` and `buildRpm`
* `SystemPackagingExtension` and `SystemPackagingBasePluginTest` each had an unused import that my IDE cleaned up (since the files were …

Add support for versioning virtual package provides to DEB packages

---

src/main/groovy/com/netflix/gradle/plugins/deb/DebCopyAction.groovy

Recently had a build* fail as a result of an obnoxiously long filename exceeding the limit for pre-posix tar (100 characters):
```
Caused by: java.lang.IllegalArgumentException: Field '../redacted/path/that/is/long/and/-/you/guessed/it/-/has/node_modules/in/it/several/times' too long, maximum is 100
```
Wanted to see if it would be reasonable to enable longer filenames. 
First time listener, first time caller to this repo—I'm not comfortable making this change as it stands but wanted to open the door with a (potential?) fix rather than just an issue.
Close with reckless abandon as necessary. 😁
\* - I can send the build link to anyone looking in here who also happens to be a coworker.

feat(jdeb): enable long filename support

---

src/main/groovy/com/netflix/gradle/plugins/deb/DebCopyAction.groovy

This reverts commit 6c36b7bfa889bc772d7219be3c106615ab51dffc.

Revert "feat(jdeb): enable long filename support"

---

src/main/groovy/com/netflix/gradle/plugins/application/OspackageApplicationSpringBootPlugin.groovy
src/test/groovy/com/netflix/gradle/plugins/application/OspackageApplicationSpringBootPluginLauncherSpec.groovy

The 'boot' distribution is a fat jar with libraries loaded from BOOT-INF/lib and has worse startup performance and is not compatible with AppCDS.

Use main distribution for Spring Boot 2+ applications

---

src/main/groovy/com/netflix/gradle/plugins/application/OspackageApplicationSpringBootPlugin.groovy
src/test/groovy/com/netflix/gradle/plugins/application/OspackageApplicationSpringBootPluginLauncherSpec.groovy

Use the `springBoot` extension to configure the application plugin allowing backwards compatibility with existing projects.

Previous users of this plugin might have used the springBoot extension

---

src/main/groovy/com/netflix/gradle/plugins/application/OspackageApplicationSpringBootPlugin.groovy
src/test/groovy/com/netflix/gradle/plugins/application/OspackageApplicationSpringBootPluginLauncherSpec.groovy

Applying recommendation from spring documentation https://docs.spring.io/spring-boot/docs/current/gradle-plugin/reference/htmlsingle/#packaging-executable-and-normal

bootJar and jar task output name is the same which can cause overriding and bundling wrong jar in debian

---

src/main/groovy/com/netflix/gradle/plugins/packaging/SystemPackagingTask.groovy

This is a simple fix for #393 by just moving the build logic referenced by super.copy() directly into `SystemPackagingTask.copy`

Fix StackOverflowError in  SystemPackagingTask when using Gradle 7.0 milestones

---

src/main/groovy/com/netflix/gradle/plugins/packaging/SystemPackagingTask.groovy

Using convention mapping has been deprecated in Gradle 7.1. This PR makes the task specific archive file configuration Gradle 7.1 compliant.

Make SystemPackagingTask archive file config gradle 7 compatible

---

src/main/groovy/com/netflix/gradle/plugins/application/OspackageApplicationSpringBootPlugin.groovy
src/test/groovy/com/netflix/gradle/plugins/application/OspackageApplicationSpringBootPluginLauncherSpec.groovy

mainClassName is a weird magical legacy property and Spring Boot 2.6.0 and later removes their version of mainClassName so this ensures that we're always reflecting the most explicit configuration in this order:
- application.mainClass
- springBoot.mainClass
- springBoot.mainClassName
- mainClassName

Improve mainClass/mainClassName logic

---

src/main/resources/deb/preinst.ftl

The intention of this PR is to fix the following issue: https://github.com/nebula-plugins/gradle-ospackage-plugin/issues/251

preinst should run during upgrade

---

src/main/groovy/com/netflix/gradle/plugins/deb/DebCopyAction.groovy
src/main/groovy/com/netflix/gradle/plugins/packaging/CopySpecEnhancement.groovy
src/main/groovy/com/netflix/gradle/plugins/packaging/SystemPackagingExtension.groovy
src/main/groovy/com/netflix/gradle/plugins/packaging/SystemPackagingTask.groovy
src/main/groovy/com/netflix/gradle/plugins/rpm/RpmCopyAction.groovy

With gradle 8.3 it is no longer possible to configure setgid via dirMode using 02000 permissions. This PR addresses this by introducing a dedicated property to enable setgid support. This issue is blocking our team (elasticsearch) to update to gradle 8.3. We tested this in our elasticsearch build already with a snapshots of this plugin using jitpack
see https://github.com/elastic/elasticsearch/pull/97838

Add explicit setgid support to Rpm and Deb tasks

---

src/main/groovy/com/netflix/gradle/plugins/packaging/AbstractPackagingCopyAction.groovy
src/main/groovy/com/netflix/gradle/plugins/packaging/SystemPackagingTask.groovy
src/test/groovy/com/netflix/gradle/plugins/rpm/RpmPluginIntegrationTest.groovy

this PR fixes issue 416,  we should be able to define `directory` directly in the ospackage extension.

fix issue 416 - merge directories from extension to task configuration

---

src/main/groovy/com/netflix/gradle/plugins/packaging/Link.groovy
src/main/groovy/com/netflix/gradle/plugins/packaging/SystemPackagingExtension.groovy
src/main/groovy/com/netflix/gradle/plugins/rpm/RpmCopyAction.groovy

Adds possibility to add user and permissionGroup to symlinks in rpm, defaults to task settings.
* Resolves #320.

Add user and group to symlinks in rpm

---

src/main/groovy/com/netflix/gradle/plugins/deb/DebCopyAction.groovy
src/main/groovy/com/netflix/gradle/plugins/rpm/RpmCopyAction.groovy

fix #437 by properly evaluating `setgid` as a Boolean

Fix #437: Properly evaluate setgid property

---

src/main/groovy/com/netflix/gradle/plugins/deb/DebCopyAction.groovy
src/main/groovy/com/netflix/gradle/plugins/packaging/SystemPackagingExtension.groovy
src/main/groovy/com/netflix/gradle/plugins/rpm/RpmCopyAction.groovy
src/test/groovy/com/netflix/gradle/plugins/rpm/RpmPluginIntegrationTest.groovy

This fixes an incompatibility with Gradle 8.8 which threw a deprecation warning and fixes an issue in setgid handling where 
fallback is never triggered

Fix dirMode handling and setgid fallback

---

gradle/wrapper/gradle-wrapper.properties
gradlew
gradlew.bat
src/test/groovy/com/netflix/gradle/plugins/deb/DebPluginLauncherSpec.groovy
src/test/groovy/com/netflix/gradle/plugins/rpm/RpmPluginIntegrationTest.groovy

Upgrade Gradle Wrapper to 8.12-rc-1
Use this link to re-run the recipe: https://app.moderne.io/recipes/org.openrewrite.gradle.UpdateGradleWrapper?organizationId=ZmEzOTAwZTUtNjc2Yi00YmFlLTkwYTgtMGE2N2YzNzljYWQw#defaults=W3sidmFsdWUiOiI4LjEyLXJjLTEiLCJuYW1lIjoidmVyc2lvbiJ9LHsidmFsdWUiOiJiaW4iLCJuYW1lIjoiZGlzdHJpYnV0aW9uIn1d

Upgrade Gradle Wrapper to 8.12-rc-1

---

src/main/groovy/com/netflix/gradle/plugins/deb/Deb.groovy
src/main/groovy/com/netflix/gradle/plugins/deb/DebCopyAction.groovy
src/main/groovy/com/netflix/gradle/plugins/docker/SystemPackageDockerfile.groovy
src/main/groovy/com/netflix/gradle/plugins/packaging/SystemPackagingTask.groovy
src/main/groovy/com/netflix/gradle/plugins/rpm/Rpm.groovy

While testing gradle 8.12 rc 1 & 2 we realised they introduced a few more deprecations and that broke our build.
This fixes the deprecation warnings we saw. We use jitpack to test this in our build here: https://github.com/elastic/elasticsearch/pull/118683
- We should not reference project from task execution phase

Fix Gradle 8.12 deprecation warning
